to_do_prvi:
    resource: "@ToDoPrviBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

account_register:
    path:     /register
    defaults: { _controller: ToDoPrviBundle:Account:register }

account_create:
    path:     /register/create
    defaults: { _controller: ToDoPrviBundle:Account:create }

logout:
    path: /logout